service: epsagon-acceptance

provider:
  name: aws
  runtime: ${opt:runtime}
  region: ${opt:region, 'us-east-1'}
  stage: ${self:custom.buildNumber}-${opt:runtimeName}
  environment:
    STAGE: dev
    EPSAGON_DEBUG: "TRUE"
  package:
    exclude:
    - './**'
    - 'node_modules/**'

custom:
  buildNumber: ${opt:buildNumber}
  pythonRequirements:
    dockerizePip: non-linux
    dockerSsh: true

functions:
  sanity:
    handler: handler.sanity
  labels:
    handler: handler.labels
  logging:
    handler: handler.logging_test

plugins:
  - serverless-python-requirements
