service: epsagon-acceptance-${self:custom.buildNumber}-${self:custom:runtime}

provider:
  name: aws
  runtime: ${opt:runtime}
  region: ${opt:region, 'us-east-1'}
  stage: dev
  role: pythonAcceptanceRole
  environment:
    STAGE: dev
    EPSAGON_DEBUG: "TRUE"
  package:
    exclude:
    - './**'
    - 'node_modules/**'

custom:
  buildNumber: ${opt:buildNumber}
  runtime: ${opt:runtime}
  pythonRequirements:
    dockerizePip: non-linux
    dockerSsh: true

functions:
  sanity:
    handler: handler.sanity
  labels:
    handler: handler.labels

resources:
  Resources:
    pythonAcceptanceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: pythonAcceptanceRole-${self:custom.buildNumber}-${self:custom:runtime}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                -  Effect: "Allow"
                   Action:
                     - "s3:PutObject"
                   Resource:
                     Fn::Join:
                       - ""
                       - - "arn:aws:s3:::"
                         - "Ref" : "ServerlessDeploymentBucket"

plugins:
  - serverless-python-requirements
